version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    depends_on:
      - logic
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "1.0"

  logic:
    build: ./logic
    ports:
      - "5000:5000"
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "0.5"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
